app/djboiler/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', include('home.urls')),
    path('oauth/', include('oauth.urls')),
    path('admin/', admin.site.urls),
    path('flower/', RedirectView.as_view(url='/flower/'), name='flower'),
    path('discord/', RedirectView.as_view(url=settings.DISCORD_INVITE), name='discord'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('debug/', include(debug_toolbar.urls))] + urlpatterns

app/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='index'),
    path('about/', views.about_view, name='about'),
]

app/oauth/urls.py
from django.urls import path
from . import views

app_name = 'oauth'

urlpatterns = [
    path('', views.oauth_start, name='login'),
    path('local/', views.oauth_local, name='local'),
    path('logout/', views.oauth_logout, name='logout'),
    path('callback/', views.oauth_callback, name='callback'),
]

app/oauth/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    avatar_hash = models.CharField(null=True, blank=True, max_length=32)
    access_token = models.CharField(null=True, blank=True, max_length=32)
    refresh_token = models.CharField(null=True, blank=True, max_length=32)
    expires_in = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.username

app/oauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username',)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=128)
    password = forms.CharField(max_length=128)

app/home/views.py
import logging
from django.shortcuts import render

logger = logging.getLogger('app')


def home_view(request, **kwargs):
    # View /
    return render(request, 'home.html')


def about_view(request, **kwargs):
    # View /about/
    return render(request, 'about.html')

app/oauth/views.py
import requests
import logging
import urllib.parse
from datetime import datetime, timedelta
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import HttpResponse, HttpResponseRedirect, redirect
from django.views.decorators.http import require_http_methods
from .models import CustomUser
from .forms import LoginForm

logger = logging.getLogger('app')


def oauth_start(request):
    # View  /oauth/
    request.session['login_redirect_url'] = get_next_url(request)
    params = {
        'client_id': settings.OAUTH_CLIENT_ID,
        'redirect_uri': settings.OAUTH_REDIRECT_URI,
        'response_type': 'code',
        'scope': settings.OAUTH_SCOPE,
    }
    url_params = urllib.parse.urlencode(params)
    url = f'https://discord.com/api/oauth2/authorize?{url_params}'
    return HttpResponseRedirect(url)


@require_http_methods(['POST'])
def oauth_local(request):
    # View  /oauth/local/
    request.session['login_redirect_url'] = get_next_url(request)
    form = LoginForm(request.POST)
    if not form.is_valid():
        logger.debug(form.errors)
        return HttpResponse(status=400)

    user = authenticate(
        request,
        username=form.cleaned_data['username'],
        password=form.cleaned_data['password'],
    )
    if not user:
        return HttpResponse(status=401)
    login(request, user)
    messages.info(request, f'Successfully logged in as {user.username}.')
    return HttpResponse()


def oauth_callback(request):
    # View  /oauth/callback/
    if 'code' not in request.GET:
        messages.warning(request, 'Uer aborted or error during login.')
        return HttpResponseRedirect(get_login_redirect_url(request))
    try:
        auth_data = get_access_token(request.GET['code'])
        profile = get_user_profile(auth_data)
        user = login_user(request, profile)
        messages.info(request, f'Successfully logged in as {user.first_name}.')
    except Exception as error:
        logger.exception(error)
        messages.error(request, f'Exception during login: {error}')
    return HttpResponseRedirect(get_login_redirect_url(request))


@require_http_methods(['POST'])
def oauth_logout(request):
    # View  /oauth/logout/
    next_url = get_next_url(request)
    # Hack to prevent login loop when logging out on a secure page
    logger.debug('next_url: %s', next_url.split('/')[1])
    if next_url.split('/')[1] in ['dashboard']:
        next_url = '/'
    request.session['login_next_url'] = next_url
    logout(request)
    messages.info(request, 'You have logged out.')
    return redirect(next_url)


def login_user(request, profile):
    # Login or create user
    user, _ = CustomUser.objects.get_or_create(username=profile['id'])
    update_profile(user, profile)
    login(request, user)
    return user


def get_access_token(code):
    # Post OAuth code and Return access_token
    url = f'{settings.DISCORD_API_URL}/oauth2/token'
    data = {
        'client_id': settings.OAUTH_CLIENT_ID,
        'client_secret': settings.OAUTH_CLIENT_SECRET,
        'grant_type': settings.OAUTH_GRANT_TYPE,
        'redirect_uri': settings.OAUTH_REDIRECT_URI,
        'code': code,
    }
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    r = requests.post(url, data=data, headers=headers, timeout=10)
    if not r.ok:
        logger.info('status_code: %s', r.status_code)
        logger.error('content: %s', r.content)
        r.raise_for_status()
    return r.json()


def get_user_profile(data):
    # Get Profile for Authenticated User
    url = f'{settings.DISCORD_API_URL}/users/@me'
    headers = {'Authorization': f"Bearer {data['access_token']}"}
    r = requests.get(url, headers=headers, timeout=10)
    if not r.ok:
        logger.info('status_code: %s', r.status_code)
        logger.error('content: %s', r.content)
        r.raise_for_status()
    p = r.json()
    return {
        'id': p['id'],
        'username': p['username'],
        'discriminator': p['discriminator'],
        'avatar': p['avatar'],
        'access_token': data['access_token'],
        'refresh_token': data['refresh_token'],
        'expires_in': datetime.now() + timedelta(0, data['expires_in']),
    }


def update_profile(user, profile):
    # Update Django user profile with provided data
    user.first_name = profile['username']
    user.last_name = profile['discriminator']
    user.avatar_hash = profile['avatar']
    user.access_token = profile['access_token']
    user.save()
    return


def get_next_url(request):
    # Determine 'next' parameter
    if 'next' in request.GET:
        return request.GET['next']
    if 'next' in request.POST:
        return request.POST['next']
    if 'next_url' in request.session:
        return request.session['next_url']
    return '/'


def get_login_redirect_url(request):
    # Determine 'login_redirect_url' parameter
    next_url = '/'
    if 'login_redirect_url' in request.session:
        next_url = request.session['login_redirect_url']
    return next_url

app/templates/about.html
{% extends "main.html" %}
{% block about_active %}active{% endblock %}
{% block title %}About{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="container mt-2">

        <h1 class="display-4">About</h1>
        <p class="lead">Django 3.2 Boiler Plate using Bootstrap 5, Celery 5 and much more...</p>

    </div>
{% endblock %}

app/templates/home.html
{% extends "main.html" %}
{% block home_active %}active{% endblock %}
{% block title %}Home{% endblock %}
{% load home_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="container mt-2">

        <h1 class="display-4">Django Boiler</h1>
        <p class="lead">Hello and welcome to Django Boiler.</p>

    </div>
{% endblock %}

app/templates/main.html
{% load static %}
{% load home_tags %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% get_config "DEBUG" as debug_enabled %}{% if debug_enabled %}
        <meta name="robots" content="noindex, nofollow">{% endif %}

    <title>Django Boiler - {% block title %}{% endblock %}</title>

    {% block meta %}
        <meta name="author" content="Shane"/>
        <meta name="title" content="Django Boiler"/>
        <meta name="description" content="Django 3.2 Boiler Plate using Bootstrap 5, Celery 5 and much more..."/>

        <meta property="og:author" content="Shane">
        <meta property="og:title" content="Django Boiler">
        <meta property="og:description" content="Django 3.2 Boiler Plate using Bootstrap 5, Celery 5 and much more...">
        <meta property="og:type" content="website">
        <meta property="og:url" content="{{ request.META|get_scheme }}://{{ request.META.HTTP_HOST }}{% url 'home:index' %}">
        <meta property="og:image" content="{{ request.META|get_scheme }}://{{ request.META.HTTP_HOST }}{% static 'images/logo128.webp' %}">
    {% endblock %}

    <script src="{% static 'main/js/theme.js' %}"></script>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static request.COOKIES.theme|theme_css %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">

    {% block head %}{% endblock %}
</head>
<body class="d-flex flex-column h-100">

{% block navbar %}
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:index' %}">
                <img src="{% static 'images/logo128.webp' %}" width="30" height="30" alt="Carl"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                    <li class="nav-item"><a class="nav-link {% block home_active %}{% endblock %}" href="{% url 'home:index' %}">
                        Home</a></li>
                    <li class="nav-item"><a class="nav-link {% block about_active %}{% endblock %}" href="{% url 'home:about' %}">
                        About</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Resources <i class="fas fa-angle-down mx-1"></i></a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
                            <li><a class="dropdown-item" href="{% get_config "DISCORD_INVITE" %}" target="_blank">
                                Join our <i class="fab fa-discord"></i> Discord <i class="fas fa-external-link-alt me-1"></i></a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="https://github.com/cssnr/django3-boiler" target="_blank">
                                View on <i class="fab fa-github"></i> GitHub <i class="fas fa-external-link-alt me-1"></i></a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdown2" role="button"
                               data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                                Log In <i class="fas fa-angle-down mx-1"></i></a>
                            <div class="dropdown-menu dropdown-menu-end" style="min-width: 300px;">
                                <div class="d-grid gap-2 p-2">
                                    <a href="{% url 'oauth:login' %}?next={{ request.path }}" class="btn btn-primary btn-lg" role="button">
                                        Log In with Discord <i class="fab fa-discord"></i></a>
                                </div>
                                <div class="dropdown-divider"></div>
                                <form class="p-2" method="post" action="{% url 'oauth:local' %}" id="login-form">
                                    {% csrf_token %}
                                    <div class="mb-1">
                                        <label for="username" class="form-label sr-only">Username</label>
                                        <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                                    </div>
                                    <div class="mb-1">
                                        <label for="password" class="form-label sr-only">Password</label>
                                        <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                                    </div>
                                    <div class="d-grid gap-2">
                                        <button type="submit" class="btn btn-outline-secondary" id="login-submit">Log In Locally</button>
                                    </div>
                                </form>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}
                                <i class="fas fa-angle-down mx-1"></i>
                                <img src="{{ user.avatar_hash|avatar_url:user.username }}" height="26" width="26" alt="P"
                                     class="rounded-circle mx-2 d-none d-sm-inline d-md-inline d-lg-inline d-xl-inline"></a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown2">
                                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#user-info-modal">
                                    <i class="fas fa-user-circle mr-2"></i> Profile</a></li>
                                {% if request.user.is_superuser %}
                                    <div class="dropdown-divider"></div>
                                    <li><a class="dropdown-item text-warning" href="{% url 'admin:index' %}">
                                        <i class="fas fa-tools mr-2"></i> Admin</a></li>
                                    <li><a class="dropdown-item text-warning" href="{% url 'flower' %}" target="_blank">
                                        <i class="fas fa-seedling mr-2"></i> Flower <i class="fas fa-external-link-alt me-1"></i></a></li>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <li><a class="dropdown-item log-out text-danger" href="#">
                                    <i class="fas fa-sign-out-alt mr-2"></i> Log Out</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    <li class="nav-item" id="light-switch">
                        {% if request.COOKIES.theme == 'dark' %}
                            <a class="nav-link" href="#"><span class="d-xl-none d-lg-none d-md-none me-2">Lights On</span>
                                <i class="fas fa-sun"></i></a>
                            <input type="hidden" id="light-switch-value" value="light">
                        {% else %}
                            <a class="nav-link" href="#"><span class="d-xl-none d-lg-none d-md-none me-2">Lights Off</span>
                                <i class="fas fa-moon"></i></a>
                            <input type="hidden" id="light-switch-value" value="dark">
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
{% endblock %}

<main class="flex-shrink-0">
    {% block messages %}{% if messages %}
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags|tag_to_class }} alert-dismissible fade show mt-2" role="alert">
                    {{ message }} <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}{% endblock %}

    {% block body %}{% endblock %}
</main>

{% block footer %}
<footer class="footer mt-auto pt-3 pb-2 ">
    <div class="container-fluid">
        <div class="row px-3">
            <div class="col-12 col-lg-6 col-md-6 col-sm-6">
                <p>For more info join our <i class="fab fa-discord"></i>
                    <a href="{% get_config "DISCORD_INVITE" %}" target="_blank">
                        Discord</a>.</p>
            </div>
            <div class="col-12 col-lg-6 col-md-6 col-sm-6 text-lg-end text-md-end text-sm-end">
                <ul class="list-inline">
                    <li class="list-inline-item"><a href="{% url 'home:index' %}">Home</a></li>
                    <li class="list-inline-item">|</li>
                    <li class="list-inline-item"><a href="{% url 'home:about' %}">About</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

{% if request.user.is_authenticated %}
    <form id="log-out" action="{% url 'oauth:logout' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.get_full_path }}">
    </form>
    <div class="modal fade" id="user-info-modal" tabindex="-1" aria-labelledby="user-info-modal-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="user-info-modal-label">
                        <i class="fas fa-user-circle mr-2"></i> Profile</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img src="{{ user.avatar_hash|avatar_url:user.username }}" alt="Profile Picture"
                         class="rounded float-end m-2" style="max-height:128px;max-width:128px;">
                    <h4 class="modal-title">{% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</h4>
                    <p>Information provided by Discord.</p>
                    <p></p>
                    <div class="clearfix"></div>
                    <table class="table mt-2">
                        <tbody>
                        <tr>
                            <th>Discord ID</th>
                            <td>{{ user.username }}</td>
                        </tr>
                        <tr>
                            <th>Discord Username</th>
                            <td>{{ user.first_name }}#{{ user.last_name }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="https://discord.com/login" class="btn btn-primary me-auto" role="button" target="_blank">
                        Open in Discord <i class="fas fa-external-link-alt me-1"></i></a>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% block js %}
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'popper/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'font-awesome/js/all.min.js' %}"></script>
    <script src="{% static 'main/js/main.js' %}"></script>
{% endblock %}

{% block tail %}{% endblock %}

</body>
</html>